name: "Unittests"

on:
  push:
    branches: [main]
  pull_request: {}
jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Install uv
        uses: astral-sh/setup-uv@v10.0.1
        with:
          python-version: "3.14"
      - name: Run the Unit Tests
        env:
          PYTHONPATH: src
        run: |
          uv run --locked --group tests pytest
